# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pre-Release

on:
  push:
    tags:
      - "v*.*.*-pre*"
      - "v*.*.*-alpha*"
      - "v*.*.*-beta*"
      - "v*.*.*-rc*"

jobs:

  deploy-prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy for Testing
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site/updates
        clean: false
    - name: Assign build.version.properties to env variable
      run: cat site/updates/testing/build.version.properties >> $GITHUB_ENV
    - name: Pre-Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        prerelease: true
        body: |
          ### Help wanted with testing of the build **${{ env.build_version_full }}**
          
          It is available at the testing update site now: `http://anb0s.github.io/EasyShell/testing`
          Exact version only site: `http://anb0s.github.io/EasyShell/testing/${{ env.build_version_path }}`
          Version: `EasyShell ${{ env.build_version_full }}`
          
          **Use "Help | Install New Software...", paste the link and select the right version!**
          
          ### All fixed issues 
          
          [milestone ${{ env.build_version_unqualified }}](https://github.com/anb0s/EasyShell/milestone/${{ env.build_version_milestone }}?closed=1)
        artifacts: "${{ env.build_version_path }}"
